---
sidebar: sidebar 
permalink: reference_kpls.html 
keywords: 'what"s new, features, new, release notes, known, problems, limitations, application' 
summary: SaaS Backup for Microsoft 365 では、新機能、拡張機能、およびバグ修正を提供する新しいリリースが定期的に導入されています。 
---
= 既知の問題および制限
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下は、 SaaS Backup for Microsoft 365 のアプリケーションレベルにおける既知の制限事項です。



== SharePoint Online の場合

SaaS Backup では、アーカイブされた SharePoint サイトのバックアップはサポートされていません。



== OneDrive for Business の場合

新しく追加したドライブは、サービスの同期を手動で完了するまで検出されません。



== Exchange Online の場合

* 140 MB を超えるメッセージが含まれているメールボックスのリストアでは、アップロードに失敗します。
* SaaS Backup では、パブリックフォルダのバックアップはサポートされていません。
* * 詳細検索 * は Exchange Online でのみ使用できます。この設定は、デフォルトでは無効になっています。この機能を有効にするよう、お客様から依頼を受ける必要があります。[ 高度な検索を有効にする *] 設定を有効にした後、管理者は個々のユーザーに対して手動で検索機能を有効にする必要があります。




== チームのために

* チャネル構成は復元されますが、コンテンツと会話は復元されません。
* API の制限により、 SaaS Backup ではパブリックチャネルとプライベートチャネルを区別できません。
* 高レベルのリストアでは、メールボックスおよび SharePoint データのみがリストアされ、会話はリストアされません。
* Teams Chat では、絵文字および GIF のバックアップまたは復元はサポートされていません。
* チームチャットの会話のみエクスポートオプションは HTML にエクスポートです。会話に投稿された添付ファイルリンクは、 HTML ドキュメントには表示されません。




== OneNote の場合

* データにエクスポートすることはできません。
* インクリメンタル・バックアップ・ジョブが失敗し ' 部分的な失敗というエラー・メッセージが表示される場合がありますOneNote セクションのいくつかをバックアップできませんでした
* OneDrive のバックアップには、 .onebak ファイルのバックアップが含まれます。
* リストア統計はダウンロードできません。
* データのエクスポートとパージはサポートされていません。




== その他の問題および制限事項

次の既知の問題および制限は、 1 つのアプリケーションに限定されていません。

Microsoft 365 サービスアカウントを使用してサインアップしたすべてのユーザーに対して、次の手順を実行します。

* SaaS Backup でサポートされているのは基本認証のみです。


無償トライアルユーザの場合：

* 1 つのサービスで最大 10 個のリストアを 24 時間で実行できます。


ライセンスユーザーの場合：

* エクスポートデータのリストアは、 1 サービスあたり 24 時間以内に 10 回まで実行できます。その他のリストアオプションには制限はありません。


サイト・コレクション・グループのリストアの場合：

* サイトコレクショングループ全体が削除されると、コレクション内のプライベートグループの復元に失敗し、リストアジョブのステータスが「一部失敗」になります。 この場合、 GUI からサイトにアクセスできません。


詳細検索 * の場合：

* 検索ジョブは、 24 時間以内に最大 10 件まで指定できます。

