---
sidebar: sidebar 
permalink: task_performing_granular_level_restore_onedrive.html 
keywords: netapp, saas restores, microsoft 365, high-level restores, granular restores, Microsoft OneDrive for Business 
summary: SaaS Backup for Microsoft 365 を使用すると、 Microsoft OneDrive for Business でハイレベルかつきめ細かなリストアを実行できます。 
---
= Microsoft OneDrive for Business で詳細レベルのリストアを実行します
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Microsoft OneDrive for Business では、個々のフォルダやファイルなどの詳細なアイテムをリストやライブラリにリストアできます。OneNote ノートブックまたはグループを復元することもできます。

デフォルトでは、最新のバックアップのみがリストアに使用できます。バックアップ設定を更新して、個々のファイルの指定数のバックアップバージョンを維持できます。バックアップに指定した数よりも多くのバージョンのファイルがある場合、リストアに使用できるのは指定したバージョン数だけです。

次の表は、 OneDrive for Business の細かなレベルの項目でサポートされるリストアオプションを示しています。

[cols="64,24a,24a,24a"]
|===
| 項目のタイプ | 同じ個人用サイトにリストアします | 別の個人用サイトにリストアします | データをエクスポートします 


| シングルドライブ  a| 
はい。
 a| 
はい。
 a| 
はい。



| 複数のドライブ  a| 
いいえ
 a| 
いいえ
 a| 
いいえ



| 単一 / 複数のファイル / アイテム  a| 
はい。
 a| 
はい。
 a| 
はい。



| OneNote 単一または複数のノートブック  a| 
はい。
 a| 
はい。
 a| 
いいえ



| OneNote の 1 つまたは複数のセクショングループ  a| 
はい。
 a| 
はい。
 a| 
いいえ



| OneNote の 1 つまたは複数のセクション  a| 
はい。
 a| 
はい。
 a| 
いいえ



| OneNote のページに関する注意 : セクションレベルでのセクション復元内のページ。  a| 
いいえ
 a| 
いいえ
 a| 
いいえ

|===
.手順
. [ ダッシュボード ] で、 OneDrive ボックスの [ 保護されている * ] の上の数字をクリックします。
. リストアを実行する必要がある個人用サイトをクリックします。
. ファイルのグループを選択します。
+
グループ内の個々のフォルダまたはファイルをリストアする場合は、ファイルのグループをクリックします。フォルダ全体を復元するには、フォルダを選択します。フォルダ内の個々のファイルをリストアするには、そのファイルが格納されているフォルダを選択し、個々のファイルを選択します。

. [* リストア ] をクリックします。
. リストアオプションを選択します。
+
** * 同じ MySite * にリストアします
+
個々のファイルを同じ MySite にリストアする場合、デフォルトでは、バックアップコピーが格納された元のコンテンツの場所に、現在の日付とタイムスタンプを持つリストアフォルダが作成されます。

+
[ 既存のコンテンツの置換 ] を選択した場合、現在のデータはバックアップに完全に置き換えられます。

** * 別の MySite * に復元します
+
別の MySite にリストアする場合は、検索フィールドにデスティネーションの MySite を入力する必要があります。検索フィールドに宛先の MySite の一部を入力すると、一致する宛先の MySites の自動検索を開始できます。

** * データのエクスポート *
+
データをエクスポートする場合は、データをダウンロードする必要があります。左側のメニューの [ レポート ] に移動します。エクスポートデータジョブを検索します。[ 合計フォルダー（ Total Folders ） ] をクリックします。次に、 [* Export Data Download Link] をクリックします。zip ファイルがダウンロードされます。zip ファイルを開き、データを抽出します。

+

NOTE: [* データのエクスポート ] リストア・オプションを選択した場合、指定されたリンクは 7 日間有効で、事前認証されています。



. [* 確認 *] をクリックします。
. リストアの進捗状況を監視するには、 * ジョブの進捗状況の表示 * をクリックします。

