---
sidebar: sidebar 
permalink: task_adding_permissions_to_service_accounts.html 
keywords: netapp, saas backup, microsoft 365, add, adding, permissions, service, accounts 
summary: 必要に応じて、アカウントを追加してバックアップのパフォーマンスを向上させることができます。サービスアカウントは、同時にバックアップを効率的に実行するために使用されます。 
---
= サービスアカウントを追加します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
必要に応じて、サービスアカウントを追加してバックアップのパフォーマンスを向上させることができます。サービスアカウントは、同時にバックアップを効率的に実行するために使用されます。

.手順
. 管理者権限を持つアカウントで Microsoft 365 管理ポータルにログインします。
. アプリ起動ツールのアイコンをクリックし、 * 管理者 * をクリックします。
. 左側の [*Users*] 、 [*Active Users*] の順にクリックします。
. [ ユーザーの追加 ] をクリックして、新しいアカウントを作成します。
. 以下の手順に従ってフォームに入力します。
+
** * パスワードを作成する * を使用します。
** [ このユーザーが最初にサインインするときにパスワードを変更する * ] オプションの選択を解除します。
** ロール * カスタマイズされた管理者 * を選択します。
** [*Exchange Administrator*] および [*SharePoint Administrator*] を選択します。
** [ 製品ライセンスなしでユーザーを作成 ] を選択します。


. 新しく作成したサービスアカウントで Exchange バックアップを実行するには、新しく作成したサービスアカウントに Exchange 偽装権限を割り当てます。link:task_configuring_impersonation.html["偽装の構成"]



NOTE: OneDrive サイトと SharePoint サイトには SaaS Backup が自動的にアクセス許可を割り当てるため、アクセス許可を割り当てる必要はありません。


NOTE: このアカウントで多要素認証（ MFA ）を有効にすることができます。
