---
sidebar: sidebar 
permalink: task_viewing_history_and_activity.html 
keywords: netapp, saas backup, microsoft 365, view, viewing, jobs, history, activity, log 
summary: SaaS Backup のアクティビティとジョブ履歴のログを表示またはダウンロードできます。 
---
= ジョブ履歴とアクティビティログを表示します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SaaS Backup for Microsoft 365 には、ジョブ履歴のログと、 SaaS Backup 内で実行されたすべてのアクティビティのログが格納されます。



== ジョブ履歴を表示します

NetApp SaaS Backup for Office 365 では、過去のすべてのジョブ履歴のレポートを表示またはダウンロードできます。ジョブタイプ、サービス、開始時間、終了時間、および完了ステータスで検索をフィルタリングできます。

.手順
. 左側のナビゲーションペインで、 *Reporting* をクリックします。すべての SaaS Backup ジョブのリストが、 ［ * ジョブ履歴 * ］ タブに表示されます。
. 結果を絞り込むには、 * フィルター * をクリックします。
. [ * Select * ] ドロップダウンメニューをクリックして、フィルタを選択します。フィルタには、ポリシー、サービス、タイプ、またはステータスを使用できます。フィルタを選択すると、検索フィールドが表示されます。
. 検索条件を入力します。
. フィルタをさらに追加する場合は、 [ フィルタを追加（ Add Filter ） ] をクリックします。
. [ フィルタを適用（ Apply Filter ） ] をクリックする。フィルタ結果が表示されます。
. 任意のジョブをクリックすると、表示が展開され、ジョブの詳細が表示されます。




== アクティビティログを表示します

SaaS Backup for Microsoft 365 内で発生するすべてのアクティビティのログが格納されます。ログには、実行された各アクションの日付と、アクションを実行したユーザーの名前が含まれます。アクティビティログは、サービスおよびイベントでフィルタできます。たとえば、 Microsoft Exchange Online で発生したすべてのリストア処理を表示する必要がある場合は、アクティビティログをフィルタリングしてそれらの具体的な結果を表示できます。

.手順
. 左側のナビゲーションペインで、 *Reporting* をクリックします。
. [ アクティビティログ * （ Activity Log * ） ] タブをクリックします。すべての SaaS Backup for Microsoft 365 アクティビティのリストが表示されます。
. 結果を絞り込むには、 * フィルター * をクリックします。
. [ * Select * ] ドロップダウンメニューをクリックして、フィルタを選択します。サービスまたはイベントでフィルタできます。フィルタを選択すると、検索フィールドが表示されます。
. 検索条件を入力します。
. フィルタをさらに追加する場合は、 [ フィルタを追加（ Add Filter ） ] をクリックします。
. [ フィルタを適用（ Apply Filter ） ] をクリックする。
+
フィルタ結果が表示されます。


